lang = {"title": "Pynotepad",
        "title2": "Pynotepad - ",
        "ico": r'ico\Notepad.ico',
        "file": ("File", 0),
        "new": ("New", 0),
        "open": ("Open", 0),
        "save": ("Save", 0),
        "save_as": ("Save As", 5),
        "print": ("Print", 0),
        "plugin": ("Plugin", 1),
        "exit": ("Exit", 1),
        "undo": ("Undo", 0),
        "redo": ("Redo", 0),
        "cut": ("Cut", 2),
        "copy": ("Copy", 0),
        "paste": ("Paste", 0),
        "del": ("Delete", 0),
        "sel_all": ("Select All", 7),
        "find": ("Find...", 0),
        "replace": ("Replace...", 0),
        "edit": ("Edit", 0),
        "file_info": ("File Info", 5),
        "file_infos": ("Encoding", "Row for total", "Size"),
        "font": ("Font...", 0),
        "wrap": ("Wrap", 0),
        "view": ("View", 0),
        "encoding_auto": ("Auto", 0),
        "ignore": ("Ignore Error", 0),
        "bin": ("Bin mode", 0),
        "encoding": ("Encoding", 0),
        "info": ("Info", 0),
        "copyright": ("Copyright", 0),
        "help": ("Help", 0),
        "options": "Options: ",
        "use_regexpr": "Use Regular Expressions",
        "match_case": "Match Case",
        "use_escape_char": "Use Escape Char",
        "replace_tip": "Replace With:",
        "find_tip": "Find What:",
        "find_next": "Find Next",
        "replace1": "Replace",
        "replace_all": "Replace All",
        "error": "Error",
        "find1": "Find",
        "warning": "Warning",
        "plugin_settings": "Plugin Settings",
        "enable": "Enable",
        "update": "Update Profile",
        "enable_warning": "Enable malicious plugins will damage your computer. Do you want to continue?",
        "disable": "Disable",
        "plugin_version": "Version: ",
        "restart_tip": "Prompt: Restart the software to take effect after the plugin is changed!",
        "font_settings": "Font Settings",
        "font_setting": ("Font", 0),
        "size_setting": ("Size", 0),
        "bold": ("Bold", 0),
        "italic": ("Italic", 0),
        "underline": ("Underline", 0),
        "font_effect": ("Font Effect", 5),
        "print_button": "Print",
        "sel_printer": "Select Printer:",
        "print_file": "Print File",
        "encoding_error": "Encoding error. This encoding may not support this string of text. Please go to the encoding menu to change the encoding!",
        "txt_name": "Text Document",
        "all_name": "All Types",
        "save_as_title": "Save As",
        "decoding_error": "Decoding error, please go to the encoding menu to change the decoding method!",
        "open_file_title": "Open File",
        "ask_save": "Do you want to save your changes?",
        "no_dependencies": "Missing dependencies: ",
        "topmost": ("Window Topmost", 7)}
